services:
  coordinator:
    build:
      context: .
      dockerfile: ./coordinator/Dockerfile
    container_name: coordinator
    networks:
      - backend_net # Simplificado
    ports:
      - "9000:8080"
    environment:
      - RUST_LOG=info

networks:
  backend_net:
    driver: bridge
